//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Kan.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_KAN_FORM                    101
#define IDR_MAINFRAME                   128
#define IDR_KANTYPE                     129
#define IDD_INBOX                       130
#define IDD_OUTBOX                      131
#define IDD_IN_LETTER                   132
#define IDD_OUT_LETTER                  133
#define IDR_IN                          136
#define IDR_OUT                         138
#define IDI_IN_CREATE                   142
#define IDI_OUT_CREATE                  143
#define IDI_INBOX                       144
#define IDI_OUTBOX                      145
#define IDI_COMPLETE                    146
#define IDR_INTYPE                      147
#define IDR_OUTTYPE                     148
#define IDD_RESOLUTION                  148
#define IDD_EXECUTOR                    149
#define IDD_THEME                       150
#define IDI_OK                          151
#define IDI_CANCEL                      152
#define IDI_DELETE                      153
#define IDI_FIND                        155
#define IDD_FIND                        159
#define IDD_FILTER                      160
#define IDI_FILTER                      161
#define IDD_EXEC_LIST                   162
#define IDI_SEARCH                      164
#define IDI_SAVE                        165
#define IDD_IN_LETTER_NEW               166
#define IDD_OUT_LETTER_NEW              167
#define IDI_GREEN                       168
#define IDI_RED                         169
#define IDI_GRAY                        170
#define IDD_WAIT                        171
#define IDD_USER                        172
#define IDD_DECLARANT                   173
#define IDI_INLETTER                    174
#define IDI_OUTLETTER                   176
#define IDD_STAT                        177
#define IDD_PERIOD                      179
#define IDD_CONTROL                     180
#define IDD_FILTER_OUT                  181
#define IDD_FILTER_CON                  182
#define IDD_FIND_OUT                    183
#define IDD_EDIT                        184
#define IDI_CONTROL                     186
#define IDI_PERSON                      187
#define IDI_POST2                       188
#define IDI_POST1                       189
#define IDI_POST3                       190
#define IDI_POST4                       191
#define IDI_REFRESH                     192
#define IDI_UNFIL                       193
#define IDD_DATE                        194
#define IDC_MAINTAB                     1000
#define IDC_LETTERLIST                  1002
#define IDC_TAB                         1004
#define IDC_REG_NUM                     1005
#define IDC_MREG_DATE                   1006
#define IDC_REG_DATE                    1007
#define IDC_FROM_PERSON                 1008
#define IDC_PERSON_TYPE                 1009
#define IDC_REPLY_NUM                   1009
#define IDC_MPROC_DATE                  1009
#define IDC_DOC_TYPE                    1010
#define IDC_PROC_DATE                   1010
#define IDC_DISTRICT                    1011
#define IDC_FROM                        1012
#define IDC_X_INNUM                     1013
#define IDC_MOUT_DATE                   1014
#define IDC_X_OUT_DATE                  1014
#define IDC_OUT_DATE                    1015
#define IDC_CONTENT                     1016
#define IDC_INFO                        1017
#define IDC_REG_NUM2                    1017
#define IDC_RECIEVER                    1017
#define IDC_COMBO1                      1018
#define IDC_AUTHOR                      1018
#define IDC_CONTROLTYPE                 1018
#define IDC_INFO2                       1018
#define IDC_USER                        1018
#define IDC_EDIT1                       1019
#define IDC_YEAR                        1019
#define IDC_INFO3                       1019
#define IDC_QUERY                       1019
#define IDC_DAYS                        1019
#define IDC_MSFLEXGRID1                 1020
#define IDC_DATA                        1020
#define IDC_LIST1                       1021
#define ID_SAVE                         1023
#define ID_CANCEL                       1024
#define IDC_DECL_FIND                   1025
#define IDC_REPLY_FIND                  1026
#define IDC_DATETIMEPICKER1             1027
#define IDC_BEGIN                       1027
#define IDC_SCHEDULE                    1027
#define IDC_DATE                        1027
#define IDC_DATETIMEPICKER2             1028
#define IDC_END                         1028
#define IDC_FACT                        1028
#define IDC_CHECK1                      1029
#define IDC_CREATE_NEW                  1030
#define IDC_BUTTON2                     1031
#define IDC_FIND                        1031
#define IDC_DECLARANT                   1031
#define IDC_DELETE                      1032
#define IDC_RESOLUTION                  1032
#define IDC_FILTER                      1033
#define IDC_TREE                        1033
#define IDC_CHANGE                      1034
#define IDC_SPIN                        1035
#define IDC_SAVE                        1037
#define IDC_CANCEL                      1038
#define IDC_COLOR                       1039
#define IDC_RED                         1040
#define IDC_GREEN                       1041
#define IDC_SLASH                       1042
#define IDC_GRAY                        1043
#define IDC_PREFIX                      1043
#define IDC_BUTTON_ALL                  1044
#define IDC_SPIN1                       1045
#define IDC_EQUAL                       1046
#define IDC_LIST                        1047
#define IDC_PROMT                       1048
#define IDC_ANSWER                      1049
#define IDC_RUN                         1050
#define IDC_SEND                        1052
#define IDC_DECL_TYPE                   1053
#define IDC_EXPORT                      1053
#define IDC_REGNUM_FULL                 1055
#define IDC_TOPLACE                     1056
#define IDC_INLIST                      1057
#define IDC_DEL                         1058
#define IDC_ADD                         1059
#define IDC_ADR_FIND                    1060
#define IDC_UNLOAD                      1061
#define ID_IN_CREATE                    32771
#define ID_BUTTON32772                  32772
#define ID_LETTER_CREATE                32773
#define ID_LETTER_FIND                  32774
#define ID_LETTER_DELETE                32775
#define ID_LETTER_FILTER                32776
#define ID_REPORTS_INVALID              32777
#define ID_REPORTS_CONTROL              32778
#define ID_STAT_BYUSER                  32779
#define ID_STAT_BYCONTROL               32780
#define ID_EDIT_USER                    32781
#define ID_EDIT_CONTROL                 32782
#define ID_EDIT_PERSON                  32783
#define ID_STAT_BYPERSON                32784
#define ID_STAT_BYAUTHOR                32785
#define ID_HELP_COMPACT                 32786
#define ID_EDIT_QUERY                   32787
#define ID_EDIT_MINE                    32788
#define ID_REPORTS_EXCEL                32789
#define ID_STAT_ONLINE                  32790
#define ID_LETTER_REFRESH               32791
#define ID_LETTER_UNFILTER              32792
#define ID_REPORTS_SIGN                 32793
#define ID_FILE_NEW_IN                  0xE103
#define ID_FILE_NEW_OUT                 0xE104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
